import { db } from '@/db';
import { alerts, contacts, contactBalances, transactions } from '@/db/schema';
import { eq, and, lt, gte, desc, sql, isNull } from 'drizzle-orm';
import { addDays, startOfDay, endOfDay, format, differenceInDays } from 'date-fns';
import { es } from 'date-fns/locale';
import { openai } from '@/lib/openai';

export interface SmartReminder {
  id?: number;
  type: 'collection' | 'payment' | 'followup' | 'meeting' | 'deadline' | 'pattern';
  priority: 'low' | 'medium' | 'high' | 'critical';
  contactId?: number;
  contactName?: string;
  amount?: number;
  currency?: string;
  message: string;
  dueDate?: Date;
  reason: string; // Por qué se creó este recordatorio
  autoGenerated: boolean;
}

export class ReminderEngine {
  // Genera recordatorios automáticos basados en el estado actual
  async generateSmartReminders(): Promise<SmartReminder[]> {
    const reminders: SmartReminder[] = [];

    // 1. Recordatorios de cobro (gente que debe dinero)
    const collectionsReminders = await this.generateCollectionReminders();
    reminders.push(...collectionsReminders);

    // 2. Recordatorios de pago (dinero que debemos)
    const paymentReminders = await this.generatePaymentReminders();
    reminders.push(...paymentReminders);

    // 3. Recordatorios de seguimiento (transacciones pendientes)
    const followupReminders = await this.generateFollowupReminders();
    reminders.push(...followupReminders);

    // 4. Recordatorios basados en patrones
    const patternReminders = await this.generatePatternReminders();
    reminders.push(...patternReminders);

    // Ordenar por prioridad
    return reminders.sort((a, b) => {
      const priorityOrder = { critical: 0, high: 1, medium: 2, low: 3 };
      return priorityOrder[a.priority] - priorityOrder[b.priority];
    });
  }

  // Genera recordatorios de cobro
  private async generateCollectionReminders(): Promise<SmartReminder[]> {
    const reminders: SmartReminder[] = [];

    // Obtener todos los saldos donde nos deben dinero
    const debtors = await db
      .select({
        contact: contacts,
        balance: contactBalances,
      })
      .from(contactBalances)
      .innerJoin(contacts, eq(contactBalances.contactId, contacts.id))
      .where(sql`CAST(${contactBalances.theyOweMe} AS DECIMAL) > 0`);

    for (const { contact, balance } of debtors) {
      const amount = parseFloat(balance.theyOweMe || '0');
      const daysSinceLastTransaction = balance.lastTransactionAt
        ? differenceInDays(new Date(), new Date(balance.lastTransactionAt))
        : 999;

      // Determinar prioridad basada en monto y tiempo
      let priority: SmartReminder['priority'] = 'low';
      let reason = '';

      if (amount > 100000 || daysSinceLastTransaction > 30) {
        priority = 'critical';
        reason = amount > 100000
          ? `Monto alto ($${amount.toLocaleString()}) pendiente`
          : `Deuda de más de 30 días`;
      } else if (amount > 50000 || daysSinceLastTransaction > 14) {
        priority = 'high';
        reason = `Deuda de ${daysSinceLastTransaction} días`;
      } else if (amount > 10000 || daysSinceLastTransaction > 7) {
        priority = 'medium';
        reason = `Cobro pendiente hace ${daysSinceLastTransaction} días`;
      } else {
        reason = 'Saldo pendiente';
      }

      reminders.push({
        type: 'collection',
        priority,
        contactId: contact.id,
        contactName: contact.name,
        amount,
        currency: balance.currency || 'MXN',
        message: `Cobrar a ${contact.name}: $${amount.toLocaleString()} MXN`,
        reason,
        autoGenerated: true,
      });
    }

    return reminders;
  }

  // Genera recordatorios de pago
  private async generatePaymentReminders(): Promise<SmartReminder[]> {
    const reminders: SmartReminder[] = [];

    // Obtener todos los saldos donde debemos dinero
    const creditors = await db
      .select({
        contact: contacts,
        balance: contactBalances,
      })
      .from(contactBalances)
      .innerJoin(contacts, eq(contactBalances.contactId, contacts.id))
      .where(sql`CAST(${contactBalances.iOweThem} AS DECIMAL) > 0`);

    for (const { contact, balance } of creditors) {
      const amount = parseFloat(balance.iOweThem || '0');
      const daysSinceLastTransaction = balance.lastTransactionAt
        ? differenceInDays(new Date(), new Date(balance.lastTransactionAt))
        : 999;

      let priority: SmartReminder['priority'] = 'medium';
      let reason = 'Deuda pendiente';

      if (daysSinceLastTransaction > 14) {
        priority = 'high';
        reason = `Deuda de ${daysSinceLastTransaction} días - puede afectar relación`;
      }

      reminders.push({
        type: 'payment',
        priority,
        contactId: contact.id,
        contactName: contact.name,
        amount,
        currency: balance.currency || 'MXN',
        message: `Pagar a ${contact.name}: $${amount.toLocaleString()} MXN`,
        reason,
        autoGenerated: true,
      });
    }

    return reminders;
  }

  // Genera recordatorios de seguimiento para transacciones pendientes
  private async generateFollowupReminders(): Promise<SmartReminder[]> {
    const reminders: SmartReminder[] = [];

    // Transacciones con fecha de vencimiento próxima
    const today = startOfDay(new Date());
    const nextWeek = addDays(today, 7);

    const upcomingDue = await db
      .select({
        transaction: transactions,
        contact: contacts,
      })
      .from(transactions)
      .leftJoin(contacts, eq(transactions.contactId, contacts.id))
      .where(
        and(
          eq(transactions.status, 'pending'),
          gte(transactions.dueDate, today),
          lt(transactions.dueDate, nextWeek)
        )
      );

    for (const { transaction, contact } of upcomingDue) {
      const daysUntilDue = transaction.dueDate
        ? differenceInDays(new Date(transaction.dueDate), new Date())
        : 0;

      let priority: SmartReminder['priority'] = 'medium';
      if (daysUntilDue <= 1) priority = 'critical';
      else if (daysUntilDue <= 3) priority = 'high';

      reminders.push({
        type: 'deadline',
        priority,
        contactId: contact?.id,
        contactName: contact?.name,
        amount: parseFloat(transaction.amount),
        message: `Vence en ${daysUntilDue} días: ${transaction.description}`,
        dueDate: transaction.dueDate || undefined,
        reason: `Transacción pendiente con fecha límite`,
        autoGenerated: true,
      });
    }

    // Transacciones vencidas
    const overdue = await db
      .select({
        transaction: transactions,
        contact: contacts,
      })
      .from(transactions)
      .leftJoin(contacts, eq(transactions.contactId, contacts.id))
      .where(
        and(
          eq(transactions.status, 'pending'),
          lt(transactions.dueDate, today)
        )
      );

    for (const { transaction, contact } of overdue) {
      const daysOverdue = transaction.dueDate
        ? differenceInDays(new Date(), new Date(transaction.dueDate))
        : 0;

      reminders.push({
        type: 'deadline',
        priority: 'critical',
        contactId: contact?.id,
        contactName: contact?.name,
        amount: parseFloat(transaction.amount),
        message: `VENCIDO hace ${daysOverdue} días: ${transaction.description}`,
        dueDate: transaction.dueDate || undefined,
        reason: `Transacción vencida`,
        autoGenerated: true,
      });
    }

    return reminders;
  }

  // Genera recordatorios basados en patrones detectados
  private async generatePatternReminders(): Promise<SmartReminder[]> {
    const reminders: SmartReminder[] = [];

    try {
      // Obtener transacciones del último mes para detectar patrones
      const lastMonth = addDays(new Date(), -30);

      const recentTransactions = await db
        .select({
          transaction: transactions,
          contact: contacts,
        })
        .from(transactions)
        .leftJoin(contacts, eq(transactions.contactId, contacts.id))
        .where(gte(transactions.createdAt, lastMonth))
        .orderBy(desc(transactions.createdAt))
        .limit(100);

      // Usar IA para detectar patrones
      if (recentTransactions.length > 10) {
        const transactionSummary = recentTransactions.map(({ transaction, contact }) => ({
          type: transaction.type,
          amount: transaction.amount,
          contact: contact?.name,
          date: transaction.transactionDate,
          category: transaction.category,
        }));

        const response = await openai.chat.completions.create({
          model: 'gpt-4-turbo-preview',
          messages: [
            {
              role: 'system',
              content: `Analiza estas transacciones y detecta patrones importantes.
Busca:
1. Clientes que suelen pagar en ciertas fechas
2. Pagos recurrentes que podrían venir pronto
3. Personas con las que hay transacciones frecuentes
4. Montos típicos por categoría
5. Cualquier anomalía o patrón sospechoso

Genera recordatorios proactivos basados en los patrones.

Responde en JSON:
{
  "patterns": [
    {
      "type": "pattern",
      "description": "qué patrón detectaste",
      "action": "qué recordatorio crear",
      "priority": "low|medium|high",
      "contactName": "si aplica"
    }
  ]
}`,
            },
            {
              role: 'user',
              content: JSON.stringify(transactionSummary, null, 2),
            },
          ],
          temperature: 0.3,
          response_format: { type: 'json_object' },
        });

        const result = JSON.parse(response.choices[0].message.content || '{}');

        for (const pattern of result.patterns || []) {
          reminders.push({
            type: 'pattern',
            priority: pattern.priority || 'low',
            contactName: pattern.contactName,
            message: pattern.action,
            reason: pattern.description,
            autoGenerated: true,
          });
        }
      }
    } catch (error) {
      console.error('Error generating pattern reminders:', error);
    }

    return reminders;
  }

  // Guarda los recordatorios generados en la base de datos
  async saveReminders(reminders: SmartReminder[]): Promise<void> {
    for (const reminder of reminders) {
      // Verificar si ya existe un recordatorio similar
      const existing = await db
        .select()
        .from(alerts)
        .where(
          and(
            eq(alerts.type, reminder.type),
            reminder.contactId
              ? eq(alerts.contactId, reminder.contactId)
              : isNull(alerts.contactId),
            eq(alerts.isDismissed, false)
          )
        )
        .limit(1);

      if (existing.length === 0) {
        await db.insert(alerts).values({
          type: reminder.type,
          message: reminder.message,
          contactId: reminder.contactId,
          dueDate: reminder.dueDate,
        });
      }
    }
  }

  // Genera y envía el resumen diario
  async generateAndSendDailySummary(): Promise<string> {
    const reminders = await this.generateSmartReminders();

    const criticalCount = reminders.filter(r => r.priority === 'critical').length;
    const highCount = reminders.filter(r => r.priority === 'high').length;

    // Calcular totales
    const totalToCollect = reminders
      .filter(r => r.type === 'collection')
      .reduce((sum, r) => sum + (r.amount || 0), 0);

    const totalToPay = reminders
      .filter(r => r.type === 'payment')
      .reduce((sum, r) => sum + (r.amount || 0), 0);

    let summary = `📊 *RESUMEN DEL DÍA - ${format(new Date(), 'EEEE d MMMM', { locale: es })}*\n\n`;

    if (criticalCount > 0) {
      summary += `🚨 *${criticalCount} ALERTAS CRÍTICAS*\n\n`;
    }

    summary += `💰 *SALDOS PENDIENTES:*\n`;
    summary += `   Por cobrar: $${totalToCollect.toLocaleString()} MXN\n`;
    summary += `   Por pagar: $${totalToPay.toLocaleString()} MXN\n`;
    summary += `   Balance: ${totalToCollect - totalToPay >= 0 ? '+' : ''}$${(totalToCollect - totalToPay).toLocaleString()} MXN\n\n`;

    // Cobros urgentes
    const urgentCollections = reminders
      .filter(r => r.type === 'collection' && (r.priority === 'critical' || r.priority === 'high'));

    if (urgentCollections.length > 0) {
      summary += `🔴 *COBROS URGENTES:*\n`;
      for (const r of urgentCollections.slice(0, 5)) {
        summary += `   • ${r.contactName}: $${r.amount?.toLocaleString()} - ${r.reason}\n`;
      }
      summary += '\n';
    }

    // Pagos pendientes
    const payments = reminders.filter(r => r.type === 'payment');
    if (payments.length > 0) {
      summary += `💳 *PAGOS PENDIENTES:*\n`;
      for (const r of payments.slice(0, 5)) {
        summary += `   • ${r.contactName}: $${r.amount?.toLocaleString()}\n`;
      }
      summary += '\n';
    }

    // Vencimientos próximos
    const deadlines = reminders.filter(r => r.type === 'deadline');
    if (deadlines.length > 0) {
      summary += `⏰ *VENCIMIENTOS:*\n`;
      for (const r of deadlines.slice(0, 5)) {
        summary += `   • ${r.message}\n`;
      }
      summary += '\n';
    }

    // Patrones detectados
    const patterns = reminders.filter(r => r.type === 'pattern');
    if (patterns.length > 0) {
      summary += `🔮 *PREDICCIONES:*\n`;
      for (const r of patterns.slice(0, 3)) {
        summary += `   • ${r.message}\n`;
      }
      summary += '\n';
    }

    summary += `\n_Responde "detalle [nombre]" para más información de un contacto_`;

    return summary;
  }
}

export const reminderEngine = new ReminderEngine();
